- name: upgrade and  update packages
  become: true
  apt: 
   update_cache: yes
- name:  create backend directory
  file:
    path: ~/backend
    state: directory
     
- name: "unarchive backend directory"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "install node dependencies"
  commands: |
   cd backend
   npm i
- name: install ans start app
  command: |
    cd ~/backend/dist
    pm2 start main.js
