- name: upgrade and  update packages
  become: true
  apt: 
   update_cache: yes
   
- name: install rsync 
  connection: local
  package:
      name: 
        - openssh
        - rsync
      state: present
   
- name: "move files to server"
  synchronize:
    src: /root/project/backend/dist
    dest: ./udapeople
    recursive: true

- name: "move files to server"
  synchronize:
    src: /root/project/backend/dist
    dest: ./udapeople
    recursive: true
- name: install ans start app
  command: |
    npm install
    pm2 stop default
    pm2 start -f ./main.js
